### ISSUE TITLE
@RestController, @Ajax 통신

### ISSUE THREAD

**Issue by dev-dong** [dev-dong/shopping#4]
signup.html 페이지에서 Sign Up 버튼을 클릭했을 때 ajxa 통신으로 input에 있는 value를 MemberController로 넘겼습니다.
제가 생각했던 흐름은 클라이언트에서 /member/signup 요청을 하면 Membercontroller의 memberSingupPOST() 메서드가 실행되면서 DB에 insert가 일어나며, signup.html 페이지에서는 콜백함수로 /index.html로 다시 돌아가게 설정했습니다.
그런데, MemberController로 가지않고 400에러가 났습니다. url 경로를 제대로 명시한거 같은데 제가 놓친 부분이 있을까요?

**Comment by torreswoo** [comment]
@dev-dong 위 이슈 지난주에 해결한것이죠? ㅎㅎ
나중에 또 참고할수있게 한번 정리해 두시면 도움될겁니다!

**Comment by dev-dong** [comment]
넵 해결하였습니다! JSON 데이터 형식을 제대로 만들지 않고 요청을 해서 발생한 오류였습니다!
